version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cjr-postgres
    env_file:
      - .env.docker
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cjr-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cjr-backend
    ports:
      - "3001:3001"
    env_file:
      - .env.docker
    depends_on:
      - postgres
    networks:
      - cjr-network
    command: sh -c "npx prisma migrate deploy && node dist/main"

volumes:
  postgres_data:

networks:
  cjr-network:
    driver: bridge
